FROM alexellis2/go-armhf:1.7.4

RUN mkdir -p /go/src/github.com/openfaas-incubator/faas-o6s/

WORKDIR /go/src/github.com/openfaas-incubator/faas-o6s

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o faas-o6s .

FROM alpine:3.5
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=0 /go/src/github.com/openfaas-incubator/faas-o6s/faas-o6s    .

CMD ["./faas-o6s"]
