/*
Copyright 2018 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// This package is generated by client-gen with custom arguments.

// This package has the automatically generated typed clients.
package v1alpha2
