/*
Copyright 2017 OpenFaaS Project

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// This package is generated by client-gen with custom arguments.

// Package fake has the automatically generated clients.
package fake
